development:
  adapter: postgresql
  encoding: unicode
  database: my_database_development
  pool: 5
  username: Nicky
  password: nicky8086

test:
  adapter: postgresql
  encoding: unicode
  database: my_database_test
  pool: 5
  username: Nicky
  password: nicky8086

production:
  adapter: postgresql
  database: my_database_production
  pool: 5
  timeout: 5000
